// Generates src/api/schema.d.ts from webapp/api/openapi.json, the backend's
// checked-in contract. With --check it writes nothing and fails if the file is
// out of date - the frontend's half of the contract test.
//
//   npm run gen:api      after `python -m api openapi -o api/openapi.json`
//   npm run check:api
import { readFileSync, writeFileSync } from "node:fs";
import openapiTS, { astToString } from "openapi-typescript";

const spec = new URL("../../api/openapi.json", import.meta.url);
const target = new URL("../src/api/schema.d.ts", import.meta.url);
const header = "// Generated by `npm run gen:api` from webapp/api/openapi.json. Do not edit.\n\n";
const text = header + astToString(await openapiTS(spec));

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    // missing counts as out of date
  }
  if (current !== text) {
    console.error("src/api/schema.d.ts is out of date with api/openapi.json - run `npm run gen:api`.");
    process.exit(1);
  }
  console.log("src/api/schema.d.ts is up to date.");
} else {
  writeFileSync(target, text);
  console.log(`wrote ${target.pathname}`);
}
