// Generated by `npm run gen:api` from webapp/api/openapi.json. Do not edit.

export interface paths {
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forecast
         * @description The whole forecast the source has - the client picks the days it shows -
         *     as quantiles per step plus the product's pictograms.
         */
        get: operations["forecast_api_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Geocode
         * @description Places matching `q`, best first; an empty list rather than an error
         *     when nothing matches. Fine to call while the user types.
         */
        get: operations["geocode_api_geocode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness. With deep=true, also fetches from every source, uncached.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Products
         * @description The products on offer and what each can do. The first is the default.
         */
        get: operations["products_api_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schemes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Schemes
         * @description Every loaded VSUP scheme with every pictogram it can choose - enough
         *     to draw a legend that always matches the rules.
         */
        get: operations["list_schemes_api_schemes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AreaOut */
        AreaOut: {
            /** East */
            east: number;
            /** North */
            north: number;
            /** South */
            south: number;
            /** West */
            west: number;
        };
        /** CacheStats */
        CacheStats: {
            /** Entries */
            entries: number;
            /** Hits */
            hits: number;
            /** Misses */
            misses: number;
        };
        /** ClassOut */
        ClassOut: {
            /**
             * Below
             * @description Upper bound in `unit`, exclusive; none for the last class.
             */
            below: number | null;
            /** Id */
            id: string;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Detail */
            detail: string;
        };
        /** Forecast */
        Forecast: {
            deterministic_run?: components["schemas"]["Run"] | null;
            location: components["schemas"]["Location"];
            /**
             * Pictograms
             * @default {}
             */
            pictograms: {
                [key: string]: components["schemas"]["PictogramSeries"];
            };
            run: components["schemas"]["Run"];
            /** Step Hours */
            step_hours: number;
            /** Steps */
            steps: string[];
            /** Variables */
            variables: {
                [key: string]: components["schemas"]["VariableSeries"];
            };
        };
        /** GeocodeOut */
        GeocodeOut: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["Place"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            forecast_cache: components["schemas"]["CacheStats"];
            /** Products */
            products: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Upstream
             * @description With deep=true: each source's state.
             */
            upstream?: {
                [key: string]: string;
            } | null;
            /** Vsup Version */
            vsup_version: string;
        };
        /** LevelOut */
        LevelOut: {
            /**
             * Interval
             * @description The two quantiles that must fall into one class or group for this level, e.g. ['p17', 'p83'] - the middle 66 % of the members. None: the level that always applies.
             */
            interval: string[] | null;
            /** Level */
            level: number;
        };
        /** Location */
        Location: {
            /** Elevation M */
            elevation_m?: number | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name */
            name?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** OutcomeOut */
        OutcomeOut: {
            /** Class */
            class: string;
            /**
             * Condition
             * @description When a rules scheme picks it, as written in the config, in `declared_unit`.
             */
            condition: string;
            /** Level */
            level: number;
            /**
             * Pictogram
             * @description Relative to `pictogram_base`.
             */
            pictogram: string;
        };
        /** PictogramItem */
        PictogramItem: {
            /** Class */
            class: string;
            /** Level */
            level: number;
            /** Pictogram */
            pictogram: string;
        };
        /** PictogramSeries */
        PictogramSeries: {
            /** Items */
            items: components["schemas"]["PictogramItem"][];
            /** Scheme */
            scheme: string;
        };
        /** Place */
        Place: {
            /** Admin1 */
            admin1?: string | null;
            /** Country */
            country?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Elevation M */
            elevation_m?: number | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name */
            name: string;
            /** Timezone */
            timezone?: string | null;
        };
        /** ProductOut */
        ProductOut: {
            /** @description For a regional model, the box around its domain: outside it there is no forecast, inside it there usually is (rotated grids fill it only partly). null: the whole globe. */
            area: components["schemas"]["AreaOut"] | null;
            /** Default */
            default: boolean;
            /**
             * Grid Km
             * @description Grid spacing of the model, in km.
             */
            grid_km: number;
            /**
             * Horizon Days
             * @description About how far ahead a run reaches, in days.
             */
            horizon_days: number;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Members
             * @description Ensemble members the model runs.
             */
            members: number;
            /**
             * Schemes
             * @description The VSUP schemes its pictograms are drawn with.
             */
            schemes: string[];
            /** Variables */
            variables: string[];
            /**
             * Variants
             * @description What `variant` accepts for this product.
             */
            variants: string[];
        };
        /** ProductsOut */
        ProductsOut: {
            /** Products */
            products: components["schemas"]["ProductOut"][];
        };
        /** Run */
        Run: {
            /** Init Time */
            init_time?: string | null;
            /** Members */
            members?: number | null;
            /** Source */
            source: string;
        };
        /** SchemeOut */
        SchemeOut: {
            /**
             * Classes
             * @description Tree schemes: the intensity classes.
             */
            classes: components["schemas"]["ClassOut"][] | null;
            /**
             * Declared Unit
             * @description The unit the config was written in.
             */
            declared_unit: string;
            /** Description */
            description: string | null;
            /**
             * Levels
             * @description Tree schemes: what each certainty level requires, most certain first.
             */
            levels?: components["schemas"]["LevelOut"][] | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "rules" | "tree";
            /** Name */
            name: string;
            /**
             * Outcomes
             * @description Every pictogram the scheme can choose, in order.
             */
            outcomes: components["schemas"]["OutcomeOut"][];
            /**
             * Unit
             * @description The variable's canonical unit, which `classes` are given in.
             */
            unit: string;
            /** Variable */
            variable: string;
            /** Window Hours */
            window_hours: number | null;
        };
        /** SchemesOut */
        SchemesOut: {
            /**
             * Pictogram Base
             * @description URL prefix for pictogram paths; cacheable for as long as `version` holds.
             */
            pictogram_base: string;
            /** Quantiles */
            quantiles: number[];
            /** Schemes */
            schemes: components["schemas"]["SchemeOut"][];
            /**
             * Version
             * @description Changes whenever the config or one of its pictograms does.
             */
            version: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VariableSeries */
        VariableSeries: {
            /** Deterministic */
            deterministic?: number[] | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "instant" | "sum";
            /** Quantiles */
            quantiles: {
                [key: string]: number[];
            };
            /** Unit */
            unit: string;
            /** Window Hours */
            window_hours?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    forecast_api_forecast_get: {
        parameters: {
            query: {
                /** @description Rounded to 2 decimals. */
                lat: number;
                /** @description Rounded to 2 decimals. */
                lon: number;
                /** @description A product id from /api/products; default: the first. */
                product?: string | null;
                variant?: "ensemble" | "hres";
                /** @description Put into location.name as given. */
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Forecast"];
                };
            };
            /** @description The source has no data for this place. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The product lacks this variant. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The upstream source failed or sent unusable data. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The upstream source did not answer in time. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    geocode_api_geocode_get: {
        parameters: {
            query: {
                /** @description Place name; fewer than 2 characters find nothing. */
                q: string;
                lang?: "de" | "en";
                count?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeOut"];
                };
            };
            /** @description The source has no data for this place. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The upstream source failed or sent unusable data. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The upstream source did not answer in time. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: {
                deep?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description deep=true and a source is failing. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    products_api_products_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductsOut"];
                };
            };
        };
    };
    list_schemes_api_schemes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemesOut"];
                };
            };
        };
    };
}
